---
title: "MA 750 Project 1"
author: "Benjamin Draves"
date: "October 24, 2017"
output: pdf_document
fontsize: 11pt
geometry: margin=1in
---

### Problem 1 Variable Bandwidth Kernel Estimator

### (a)

Here we obtain a preliminary estimate of $f(x_i)$, $\widetilde{f}(x_i)$ using standard kernel density estimators. We consider three kenerels (Gaussian, Epanechnikov, and Triangular) along with three bandwidth, $g$, selection criterion (Rule of Thumb, Biased Cross Validation, and Maximum Likelihood Cross Validation). 

```{r}
#load in necessary libraries
library("ftnonpar")
library("kedd")

#get sample from Claw distribution
X = rclaw(100)

#set initial kernel 

k = "gaussian"
#k = "epanechnikov"
#k = "triangular"

#define initial bandwidth g 
g.rot = 1.06*sd(X)/length(X)^(1/5)
g.bcv = h.bcv(X, kernel = k)$h
g.mlcv = h.mlcv(X, kernel = k)$h 

#define ftil 
ftil = density(X, kernel = k, bw = g.bcv)
```


```{r}

#approximate ftil(X) for our sample
ftilX = approx(ftil$x, ftil$y, X)

#define kernel 
K = function(y){
	return(1/(2*pi)*exp(-(y^2)/2))	
}

#define fhat 
fhat = function(x, h){
	n = length(X)
	return((1/(n*h))*sum(sqrt(ftilX$y) * K((x-X)*sqrt(ftilX$y)/h)))
}

#get estimated kernel
x = seq(-3,3,by = .05)
f = matrix(NA, ncol = 2, nrow = length(x))
for(i in 1:nrow(f)){
	f[i,1] = x[i]
	f[i,2] = fhat(x[i], .2)
}

```


